INSERT INTO USER (NAME, LAST_NAME, EMAIL, DNI) VALUES ('Juan', 'Favaro', 'juaanfavaro@gmail.com', '41813589');

INSERT INTO STATE (NAME) VALUES ('Creado');

INSERT INTO PROJECT (NAME, DESCRIPTION, STATE_ID, ) VALUES ('Test', 'Test', 1);

INSERT INTO TASK (DESCRIPTION, USER_ID, STATE_ID, PROJECT_ID) VALUES ('Test', 1, 1, 1);

