INSERT INTO USER (NAME, LAST_NAME, DNI, EMAIL) VALUES ('Juan', 'Favaro', '41813589', 'juaanfavaro@gmail.com');

INSERT INTO USER (NAME, LAST_NAME, DNI, EMAIL) VALUES ('Test', 'Test', '12312', 'test@gmail.com');

INSERT INTO PROJECT (NAME, DESCRIPTION, STATE) VALUES ('Test', 'Test', 'CREADO');

INSERT INTO TASK (NAME, DESCRIPTION, USER_ID, STATE, PROJECT_ID) VALUES ('Test','Test', 1, 'CREADO', 1);

INSERT INTO COMMENT (TITLE, DESCRIPTION, TASK_ID, PROJECT_ID) VALUES ('Test', 'Test', 1, 1);

INSERT INTO REL_USER_PROJECT (PROJECT_ID, USER_ID) VALUES (1, 1);