INSERT INTO STATE (NAME) VALUES ('CREADO');
INSERT INTO STATE (NAME) VALUES ('ASIGNADO'); 
INSERT INTO STATE (NAME) VALUES ('CERRADO'); 
INSERT INTO STATE (NAME) VALUES ('PAUSADO');
INSERT INTO STATE (NAME) VALUES ('EN REVISION');
INSERT INTO STATE (NAME) VALUES ('TERMINADO');
